// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GoalsController from "./goals_controller"
application.register("goals", GoalsController)

import PatientTasksController from "./patient_tasks_controller"
application.register("patient-tasks", PatientTasksController)

import PolltasksController from "./polltasks_controller"
application.register("polltasks", PolltasksController)

import TaskformController from "./taskform_controller"
application.register("taskform", TaskformController)

import ToastsController from "./toasts_controller"
application.register("toasts", ToastsController)

import ConditionsController from "./conditions_controller"
application.register("conditions", ConditionsController)

import CapacityController from "./capacity_controller"
application.register("capacity", CapacityController)