module ConditionsHelper
  include SessionHelper

  def save_conditions(conditions)
    Rails.cache.write(conditions_key, conditions, expires_in: 1.hour)
  end

def description_options_condition
    {
      "language-access" => [
        ["Need for interpreter (finding)","315593009"],
        ["Interpreter needed (finding)","315594003"],
        ["Requires telephone language interpreter service (finding)","745664000"],
        ["Encounter for counseling for socioeconomic factors","Z71.88"],
        ["Persons encountering health services in other specified circumstances","Z76.89"],
      ],
      "incarceration-status" => [
          ["Problem related to release from prison (finding)","288561000119106"],
          ["Imprisonment and other incarceration","Z65.1"],
          ["Problems related to release from prison","Z65.2"],
          ["Problems related to other legal circumstances","Z65.3"],
          ["Encounter for counseling for socioeconomic factors","Z71.88"],
      ],
      "utility-insecurity" => [
          ["Lack of heat in house (finding)", "105535008"],
          ["Living in housing without electricity (finding)", "105536009"],
          ["Lack of cooling in house (finding)", "423798004"],
          ["Lack of running water in house (finding)", "5491000175103"],
          ["Unable to obtain electricity in residence due to limited financial resources (finding)", "671391000124106"],
          ["Unable to obtain water in residence due to limited financial resources (finding)", "761541000124107"],
          ["Inadequate drinking-water supply", "Z58.6"],
          ["Inadequate housing environmental temperature", "Z59.11"],
          ["Inadequate housing utilities", "Z59.12"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "digital-access" => [
          ["Unable to obtain internet service in residence due to limited financial resources (finding)", "671361000124103"],
          ["Inadequate digital access due to inadequate internet service in geographical region (finding)", "861171000124107"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "digital-literacy" => [
            ["Inadequate foundation level digital literacy skills (finding)", "851261000124100"],
            ["Encounter for counseling for socioeconomic factors", "Z71.88"],
       ],
      "medical-cost-burden" => [
          ["Financial insecurity (finding)", "1184702004"],
          ["Financial insecurity due to cost burden of medical expenses (finding)", "671281000124103"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Patient's noncompliance with dietary regimen due to financial hardship", "Z91.110"],
          ["Caregiver's intentional underdosing of patient's medication regimen due to financial hardship", "Z91.A20"],
      ],
      "health-insurance-coverage-status" => [
          ["Not enrolled in health insurance plan (finding)", "671211000124105"],
          ["Unable to obtain health insurance coverage due to limited financial resources (finding)", "761551000124109"],
          ["Insufficient health insurance coverage", "Z59.71"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "personal-health-literacy" => [
          ["Requires plain language intervention to support health literacy (finding)", "1254711005"],
          ["Requires document translation service to support health literacy (finding)", "1254712003"],
          ["Requires language interpretation service to support health literacy (finding)", "1254713008"],
          ["Requires culturally responsive service to support health literacy (finding)", "1254714002"],
          ["Requires assistive technology to support health literacy (finding)", "1254715001"],
          ["Difficulty demonstrating health literacy (finding)", "871869008"],
          ["Problems related to health literacy", "Z55.6"],
          ["Other problems related to education and literacy", "Z55.8"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "elder-abuse" => [
          ["Suspected victim of elder physical abuse (situation)", "12242911000119107"],
          ["Suspected victim of elder sexual abuse (situation)", "12399491000119102"],
          ["Suspected victim of elder emotional abuse (situation)", "12399531000119102"],
          ["Suspected victim of elder neglect (situation)", "15912911000119102"],
          ["Victim of elder physical abuse (finding)", "459601000124108"],
          ["History of victim of elder physical abuse (situation)", "459611000124106"],
          ["History of victim of elder sexual abuse (situation)", "459901000124103"],
          ["Victim of elder financial abuse (finding)", "551461000124100"],
          ["Victim of elder sexual abuse (finding)", "551471000124107"],
          ["History of victim of elder abuse (situation)", "551561000124104"],
          ["History of victim of elder financial abuse (situation)", "551571000124106"],
          ["History of victim of elder neglect (situation)", "551581000124109"],
          ["History of victim of elder emotional abuse (situation)", "551591000124107"],
          ["Suspected victim of elder financial abuse (situation)", "551601000124104"],
          ["Victim of elder abuse by unrelated caregiver (finding)", "611191000124101"],
          ["Victim of elder abuse by related caregiver (finding)", "611201000124103"],
          ["Suspected elderly person maltreatment (situation)", "697957000"],
          ["At increased risk of elder abuse (finding)", "704349002"],
          ["Victim of elder abuse (finding)", "706872008"],
          ["At increased risk of elder neglect (finding)", "706874009"],
          ["Victim of elder financial exploitation (finding)", "761141000124101"],
          ["Psychologically abused elder (finding)", "95929000"],
          ["Neglected elder (finding)", "95933007"],
          ["Adult neglect or abandonment, confirmed, initial encounter", "T74.01XA"],
          ["Adult neglect or abandonment, confirmed, subsequent encounter", "T74.01XD"],
          ["Adult neglect or abandonment, confirmed, sequela", "T74.01XS"],
          ["Adult physical abuse, confirmed, initial encounter", "T74.11XA"],
          ["Adult physical abuse, confirmed, subsequent encounter", "T74.11XD"],
          ["Adult physical abuse, confirmed, sequela", "T74.11XS"],
          ["Adult sexual abuse, confirmed, initial encounter", "T74.21XA"],
          ["Adult sexual abuse, confirmed, subsequent encounter", "T74.21XD"],
          ["Adult sexual abuse, confirmed, sequela", "T74.21XS"],
          ["Adult psychological abuse, confirmed, initial encounter", "T74.31XA"],
          ["Adult psychological abuse, confirmed, subsequent encounter", "T74.31XD"],
          ["Adult psychological abuse, confirmed, sequela", "T74.31XS"],
          ["Unspecified adult maltreatment, confirmed, initial encounter", "T74.91XA"],
          ["Unspecified adult maltreatment, confirmed, subsequent encounter", "T74.91XD"],
          ["Unspecified adult maltreatment, confirmed, sequela", "T74.91XS"],
          ["Adult financial abuse, confirmed", "T74.A1"],
          ["Adult financial abuse, confirmed, initial encounter", "T74.A1XA"],
          ["Adult financial abuse, confirmed, subsequent encounter", "T74.A1XD"],
          ["Adult financial abuse, confirmed, sequela", "T74.A1XS"],
          ["Adult neglect or abandonment, suspected, initial encounter", "T76.01XA"],
          ["Adult neglect or abandonment, suspected, subsequent encounter", "T76.01XD"],
          ["Adult neglect or abandonment, suspected, sequela", "T76.01XS"],
          ["Adult physical abuse, suspected, initial encounter", "T76.11XA"],
          ["Adult physical abuse, suspected, subsequent encounter", "T76.11XD"],
          ["Adult physical abuse, suspected, sequela", "T76.11XS"],
          ["Adult sexual abuse, suspected, initial encounter", "T76.21XA"],
          ["Adult sexual abuse, suspected, subsequent encounter", "T76.21XD"],
          ["Adult sexual abuse, suspected, sequela", "T76.21XS"],
          ["Adult psychological abuse, suspected, initial encounter", "T76.31XA"],
          ["Adult psychological abuse, suspected, subsequent encounter", "T76.31XD"],
          ["Adult psychological abuse, suspected, sequela", "T76.31XS"],
          ["Unspecified adult maltreatment, suspected, initial encounter", "T76.91XA"],
          ["Unspecified adult maltreatment, suspected, subsequent encounter", "T76.91XD"],
          ["Unspecified adult maltreatment, suspected, sequela", "T76.91XS"],
          ["Adult financial abuse, suspected", "T76.A1"],
          ["Adult financial abuse, suspected, initial encounter", "T76.A1XA"],
          ["Adult financial abuse, suspected, subsequent encounter", "T76.A1XD"],
          ["Adult financial abuse, suspected, sequela", "T76.A1XS"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Personal history of adult physical and sexual abuse", "Z91.410"],
          ["Personal history of adult psychological abuse", "Z91.411"],
          ["Personal history of adult neglect", "Z91.412"],
          ["Personal history of adult financial abuse", "Z91.413"],
          ["Personal history of unspecified adult abuse", "Z91.419"],
      ],
      "intimate-partner-violence" => [
          ["At increased risk of intimate partner violence (finding)", "22791000175108"],
          ["Adult victim of physical abuse by female partner (finding)", "288671000119101"],
          ["Adult victim of physical abuse by male partner (finding)", "288681000119103"],
          ["History of domestic physical abuse of adult (situation)", "293611000119101"],
          ["History of domestic violence (situation)", "412732008"],
          ["Victim of abusive sexual relationship with partner (finding)", "418150003"],
          ["Victim of abusive sexual relationship with husband (finding)", "419951006"],
          ["Victim of abusive sexual relationship with wife (finding)", "420180008"],
          ["Victim of physical abuse by intimate partner (finding)", "551441000124104"],
          ["Victim of emotional abuse by intimate partner (finding)", "551451000124102"],
          ["Suspected victim of abuse by intimate partner (situation)", "551481000124105"],
          ["Suspected victim of emotional abuse by intimate partner (situation)", "551491000124108"],
          ["Suspected victim of sexual abuse by intimate partner (situation)", "551501000124100"],
          ["Suspected victim of physical abuse by intimate partner (situation)", "551511000124102"],
          ["History of physical abuse by intimate partner (situation)", "551531000124108"],
          ["History of sexual abuse by intimate partner (situation)", "551541000124103"],
          ["History of emotional abuse by intimate partner (situation)", "551551000124101"],
          ["Victim of intimate partner abuse (finding)", "706893006"],
          ["At increased risk of domestic violence (finding)", "707087005"],
          ["Victim of sexual assault by intimate partner (finding)", "713820002"],
          ["History of domestic physical abuse (situation)", "720411002"],
          ["History of domestic emotional abuse (situation)", "720428004"],
          ["History of domestic sexual abuse (situation)", "720741001"],
          ["Adult physical abuse, confirmed", "T74.11"],
          ["Adult physical abuse, confirmed, initial encounter", "T74.11XA"],
          ["Adult physical abuse, confirmed, subsequent encounter", "T74.11XD"],
          ["Adult physical abuse, confirmed, sequela", "T74.11XS"],
          ["Child physical abuse, confirmed", "T74.12"],
          ["Child physical abuse, confirmed, initial encounter", "T74.12XA"],
          ["Child physical abuse, confirmed, subsequent encounter", "T74.12XD"],
          ["Child physical abuse, confirmed, sequela", "T74.12XS"],
          ["Adult sexual abuse, confirmed", "T74.21"],
          ["Adult sexual abuse, confirmed, initial encounter", "T74.21XA"],
          ["Adult sexual abuse, confirmed, subsequent encounter", "T74.21XD"],
          ["Adult sexual abuse, confirmed, sequela", "T74.21XS"],
          ["Child sexual abuse, confirmed", "T74.22"],
          ["Child sexual abuse, confirmed, initial encounter", "T74.22XA"],
          ["Child sexual abuse, confirmed, subsequent encounter", "T74.22XD"],
          ["Child sexual abuse, confirmed, sequela", "T74.22XS"],
          ["Adult psychological abuse, confirmed", "T74.31"],
          ["Adult psychological abuse, confirmed, initial encounter", "T74.31XA"],
          ["Adult psychological abuse, confirmed, subsequent encounter", "T74.31XD"],
          ["Adult psychological abuse, confirmed, sequela", "T74.31XS"],
          ["Child psychological abuse, confirmed", "T74.32"],
          ["Child psychological abuse, confirmed, initial encounter", "T74.32XA"],
          ["Child psychological abuse, confirmed, subsequent encounter", "T74.32XD"],
          ["Child psychological abuse, confirmed, sequela", "T74.32XS"],
          ["Adult financial abuse, confirmed", "T74.A1"],
          ["Adult financial abuse, confirmed, initial encounter", "T74.A1XA"],
          ["Adult financial abuse, confirmed, subsequent encounter", "T74.A1XD"],
          ["Adult financial abuse, confirmed, sequela", "T74.A1XS"],
          ["Child financial abuse, confirmed", "T74.A2"],
          ["Child financial abuse, confirmed, initial encounter", "T74.A2XA"],
          ["Child financial abuse, confirmed, subsequent encounter", "T74.A2XD"],
          ["Child financial abuse, confirmed, sequela", "T74.A2XS"],
          ["Adult physical abuse, suspected", "T76.11"],
          ["Adult physical abuse, suspected, initial encounter", "T76.11XA"],
          ["Adult physical abuse, suspected, subsequent encounter", "T76.11XD"],
          ["Adult physical abuse, suspected, sequela", "T76.11XS"],
          ["Child physical abuse, suspected", "T76.12"],
          ["Child physical abuse, suspected, initial encounter", "T76.12XA"],
          ["Child physical abuse, suspected, subsequent encounter", "T76.12XD"],
          ["Child physical abuse, suspected, sequela", "T76.12XS"],
          ["Adult sexual abuse, suspected", "T76.21"],
          ["Adult sexual abuse, suspected, initial encounter", "T76.21XA"],
          ["Adult sexual abuse, suspected, subsequent encounter", "T76.21XD"],
          ["Adult sexual abuse, suspected, sequela", "T76.21XS"],
          ["Child sexual abuse, suspected", "T76.22"],
          ["Child sexual abuse, suspected, initial encounter", "T76.22XA"],
          ["Child sexual abuse, suspected, subsequent encounter", "T76.22XD"],
          ["Child sexual abuse, suspected, sequela", "T76.22XS"],
          ["Adult psychological abuse, suspected", "T76.31"],
          ["Adult psychological abuse, suspected, initial encounter", "T76.31XA"],
          ["Adult psychological abuse, suspected, subsequent encounter", "T76.31XD"],
          ["Adult psychological abuse, suspected, sequela", "T76.31XS"],
          ["Child psychological abuse, suspected", "T76.32"],
          ["Child psychological abuse, suspected, initial encounter", "T76.32XA"],
          ["Child psychological abuse, suspected, subsequent encounter", "T76.32XD"],
          ["Child psychological abuse, suspected, sequela", "T76.32XS"],
          ["Adult financial abuse, suspected", "T76.A1"],
          ["Adult financial abuse, suspected, initial encounter", "T76.A1XA"],
          ["Adult financial abuse, suspected, subsequent encounter", "T76.A1XD"],
          ["Adult financial abuse, suspected, sequela", "T76.A1XS"],
          ["Child financial abuse, suspected", "T76.A2"],
          ["Child financial abuse, suspected, initial encounter", "T76.A2XA"],
          ["Child financial abuse, suspected, subsequent encounter", "T76.A2XD"],
          ["Child financial abuse, suspected, sequela", "T76.A2XS"],
          ["Personal history of child financial abuse", "Z62.814"],
          ["Personal history of intimate partner abuse in childhood", "Z62.815"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Personal history of adult financial abuse", "Z91.413"],
          ["Personal history of adult intimate partner abuse", "Z91.414"],
      ],
      "social-connection" => [
        ["Social withdrawal (finding)", "105411000"],
        ["Lives alone (finding)", "105529008"],
        ["Emotional support absent (finding)", "1184686008"],
        ["Family support absent (finding)", "1184687004"],
        ["At increased risk for loneliness (finding)", "129698004"],
        ["Lives alone no help available (finding)", "160726006"],
        ["Lives alone needs housekeeper (finding)", "160727002"],
        ["At increased risk for social isolation (finding)", "22761000175104"],
        ["Feeling lonely (finding)", "267076002"],
        ["Minimal outside social stimulation (finding)", "422611005"],
        ["Social isolation (finding)", "422650009"],
        ["Lacks emotional support (finding)", "422786001"],
        ["Limited social contact (finding)", "423315002"],
        ["Inadequate social support (finding)", "425022003"],
        ["No contact with family (finding)", "441879005"],
        ["Receives no social support (finding)", "445071000124105"],
        ["Lack of family support (finding)", "704489009"],
        ["Decreased social isolation (finding)", "733817003"],
        ["Social isolation in parenthood (finding)", "736769008"],
        ["Problems related to living alone", "Z60.2"],
        ["Social exclusion and rejection", "Z60.4"],
        ["Other problems related to social environment", "Z60.8"],
        ["Other specified problems related to primary support group", "Z63.8"],
        ["Other specified problems related to psychosocial circumstances", "Z65.8"],
        ["Problem related to unspecified psychosocial circumstances", "Z65.9"],
        ["Encounter for counseling for socioeconomic factors", "Z71.88"],
        ["Other specified personal risk factors, not elsewhere classified", "Z91.89"],
      ],
      "stress" => [
          ["High perceived stress (finding)", "1193534004"],
          ["Feeling stressed (finding)", "224974006"],
          ["Stress overload (finding)", "424582000"],
          ["Emotional stress (finding)", "442347009"],
          ["Stress (finding)", "73595000"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Stress, not elsewhere classified", "Z73.3"],
      ],
      "veteran-status" => [
          ["History of serving in military service (situation)", "1187600006"],
          ["History of military deployment (situation)", "1187601005"],
          ["History of exposure to combat during military service (situation)", "1187605001"],
          ["History of desertion from military service (situation)", "1187607009"],
          ["History of leaving military service (situation)", "1187610002"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Personal history of military deployment", "Z91.82"],
          ["Personal history of military service", "Z91.85"],
      ],
      "material-hardship" => [
          ["Inadequate clothing due to limited financial resources (finding)", "1230283000"],
          ["Unable to afford medication (finding)", "454061000124102"],
          ["Unable to afford visit copayment (finding)", "5311000175103"],
          ["Unable to afford glucose monitoring device (finding)", "5371000175108"],
          ["Unable to afford blood pressure monitor (finding)", "5521000175101"],
          ["Unable to afford weight scale (finding)", "5731000175109"],
          ["Unable to obtain internet service in residence due to limited financial resources (finding)", "671361000124103"],
          ["Unable to heat residence due to limited financial resources (finding)", "671371000124105"],
          ["Unable to obtain healthcare due to limited financial resources (finding)", "671381000124108"],
          ["Unable to obtain electricity in residence due to limited financial resources (finding)", "671391000124106"],
          ["Unable to cool residence due to limited financial resources (finding)", "671401000124108"],
          ["Unable to obtain telephone due to limited financial resources (finding)", "671421000124103"],
          ["Unable to obtain clinical equipment and/or device due to limited financial resources (finding)", "671431000124100"],
          ["Unable to obtain childcare due to limited financial resources (finding)", "671461000124109"],
          ["Unable to obtain adult dependent care due to limited financial resources (finding)", "671471000124102"],
          ["Unable to obtain telephone service due to limited financial resources (finding)", "671491000124101"],
          ["Unable to obtain medication (finding)", "715046004"],
          ["Unable to obtain water in residence due to limited financial resources (finding)", "761541000124107"],
          ["Basic services unavailable in physical environment", "Z58.81"],
          ["Material hardship due to limited financial resources, not elsewhere classified", "Z59.87"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Patient's intentional underdosing of medication regimen due to financial hardship", "Z91.120"],
          ["Patient's noncompliance with other medical treatment and regimen due to financial hardship", "Z91.190"],
          ["Caregiver's intentional underdosing of patient's medication regimen due to financial hardship", "Z91.A20"],
      ],
      "financial-insecurity" => [
          ["Financial insecurity (finding)", "1184702004"],
          ["Financial insecurity due to cost burden of medical expenses (finding)", "671281000124103"],
          ["Financial insecurity due to debt (finding)", "671441000124105"],
          ["Financial insecurity due to bankruptcy (finding)", "671451000124107"],
          ["Unable to obtain health insurance coverage due to limited financial resources (finding)", "761551000124109"],
          ["Financial insecurity", "Z59.86"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "transportation-insecurity" => [
          ["Transport too expensive (finding)", "160695008"],
          ["Transport distance too great (finding)", "160696009"],
          ["Transportation barrier impedes ability to use community resources (finding)", "424629004"],
          ["Transportation insecurity (finding)", "551691000124106"],
          ["Transportation insecurity due to unsafe transportation environment (finding)", "551701000124106"],
          ["Transportation insecurity due to excessive travel time to destination (finding)", "551711000124109"],
          ["Transportation insecurity due to no driver's license (finding)", "551721000124101"],
          ["Inability to access health care due to transportation insecurity (finding)", "551731000124103"],
          ["Transportation insecurity due to no access to vehicle (finding)", "551741000124108"],
          ["Inability to access community resources due to transportation insecurity (finding)", "551751000124105"],
          ["Transportation insecurity due to unaffordable transportation (finding)", "551761000124107"],
          ["Transportation insecurity due to route not serviced by public transportation (finding)", "611151000124107"],
          ["Transportation insecurity limiting access to food (finding)", "611161000124109"],
          ["Lack of access to transportation (finding)", "713458007"],
          ["Transportation insecurity", "Z59.82"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "inadequate-housing" => [
          ["Housing unsatisfactory (finding)", "105531004"],
          ["Overcrowded in house (finding)", "105532006"],
          ["Lack of heat in house (finding)", "105535008"],
          ["Living in housing without electricity (finding)", "105536009"],
          ["Infestation of place of residence (finding)", "1162585007"],
          ["Lead in residence (finding)", "1197631001"],
          ["Inadequate equipment for safe food storage in residence (finding)", "1197632008"],
          ["Inadequate food preparation equipment in residence (finding)", "1197634009"],
          ["Radon in residence (finding)", "1197636006"],
          ["Carbon monoxide in residence (finding)", "1197637002"],
          ["Inadequate smoke detection equipment in residence (finding)", "1197640002"],
          ["Inadequate carbon monoxide detection equipment in residence (finding)", "1197641003"],
          ["Lack of functioning sink in residence (finding)", "1197645007"],
          ["Lack of functioning toilet in residence (finding)", "1197646008"],
          ["Asbestos in residence (finding)", "1197647004"],
          ["Mold growth in home (finding)", "224255009"],
          ["Lack of cooling in house (finding)", "423798004"],
          ["Substandard housing caused by structural insufficiency (finding)", "471981000124106"],
          ["Residence does not meet functional needs (finding)", "471991000124109"],
          ["At risk of housing code violation (finding)", "472001000124106"],
          ["Lack of running water in house (finding)", "5491000175103"],
          ["Inadequate housing", "Z59.1"],
          ["Inadequate housing, unspecified", "Z59.10"],
          ["Inadequate housing environmental temperature", "Z59.11"],
          ["Inadequate housing utilities", "Z59.12"],
          ["Other inadequate housing", "Z59.19"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
       "homelessness" => [
            ["Homeless (finding)", "32911000"],
            ["Sheltered homelessness (finding)", "611131000124100"],
            ["Unsheltered homelessness (finding)", "611141000124105"],
            ["Homelessness, living in a shared accommodation (finding)", "611551000124102"],
            ["Homelessness unspecified", "Z59.00"],
            ["Sheltered homelessness", "Z59.01"],
            ["Unsheltered homelessness", "Z59.02"],
            ["Encounter for counseling for socioeconomic factors", "Z71.88"],
       ],
       "housing-instability" => [
           ["Housing instability (finding)", "1156191002"],
           ["Housing instability due to imminent risk of homelessness (finding)", "1156192009"],
           ["Housing instability due to frequent change in place of residence (finding)", "1156193004"],
           ["Housing instability following recent homelessness (finding)", "1156194005"],
           ["Housing instability due to being behind on payments for place of residence (finding)", "1156195006"],
           ["Housing instability due to threat of eviction (finding)", "1156196007"],
           ["Housing instability due to housing cost burden (finding)", "1187272007"],
           ["Housing insecurity (finding)", "611531000124109"],
           ["Housing instability, housed, with risk of homelessness", "Z59.811"],
           ["Housing instability, housed, homelessness in past 12 months", "Z59.812"],
           ["Housing instability, housed unspecified", "Z59.819"],
           ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "food-insecurity" => [
          ["Limited access to nutrition supplies (finding)", "1155680000"],
          ["Noncompliance with dietary regimen (finding)", "129832003"],
          ["Nutrition impaired due to limited access to healthful foods (finding)", "445281000124101"],
          ["Mild food insecurity on United States household food security survey module (finding)", "470911000124109"],
          ["Moderate food insecurity on United States household food security survey module (finding)", "470941000124108"],
          ["Severe food insecurity on United States household food security survey module (finding)", "470951000124105"],
          ["Insufficient food supply (finding)", "706875005"],
          ["Food insecurity (finding)", "733423003"],
          ["Nutritional deficiency, unspecified", "E63.9"],
          ["Food insecurity", "Z59.41"],
          ["Other specified lack of adequate food", "Z59.48"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
          ["Patient's noncompliance with dietary regimen", "Z91.11"],
          ["Patient's noncompliance with dietary regimen due to financial hardship", "Z91.110"],
          ["Caregiver's noncompliance with patient's dietary regimen due to financial hardship", "Z91.A10"],
      ],
      "educational-attainment" => [
          ["Less than a high school diploma", "Z55.5"],
          ["Other problems related to education and literacy", "Z55.8"],
          ["Failure to achieve high school degree and/or equivalent (finding)", "551651000124100"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "employment-status" => [
          ["Recently unemployed (finding)", "160899000"],
          ["Chronic unemployment (finding)", "160900005"],
          ["Unemployed (finding)", "73438004"],
          ["Not in labor force (finding)", "741062008"],
          ["Unemployment, unspecified", "Z56.0"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
      "protective-factor" => [
          ["Spiritual strength (finding)", "105572002"],
          ["Food security (finding)", "1078229009"],
          ["Extrinsic motivation (finding)", "112076007"],
          ["Has access to transportation (finding)", "1137434003"],
          ["Demonstrates knowledge of parenting (finding)", "1141694001"],
          ["Feeling more empowered (finding)", "1144481009"],
          ["Good caregiver child attachment (finding)", "1148785005"],
          ["Self efficacy (finding)", "1156332000"],
          ["Adequate social connection (finding)", "1230391007"],
          ["Not feeling lonely (finding)", "1230392000"],
          ["Adequate social participation (finding)", "1230393005"],
          ["Feels social relationships are satisfying and sufficient (finding)", "1300103006"],
          ["Lives with family (finding)", "224133007"],
          ["Lives with parents (finding)", "224137008"],
          ["Financially secure (finding)", "224165005"],
          ["Income sufficient to meet needs (finding)", "224190007"],
          ["Employed (finding)", "224363007"],
          ["Good self-image (finding)", "225509003"],
          ["Hopeful for the future (finding)", "225649001"],
          ["Empowered (finding)", "225791005"],
          ["Displays ethical principles (finding)", "225843003"],
          ["Healthy diet (finding)", "226234005"],
          ["Exercises regularly (finding)", "228448000"],
          ["Able to make friends (finding)", "26291000146108"],
          ["Satisfied with job (finding)", "302124002"],
          ["Secure attachment (finding)", "304867008"],
          ["Improvement in friendships and/or relationships (finding)", "406542000"],
          ["Receives as much social support as wanted (finding)", "445091000124106"],
          ["Feeling safe (finding)", "449892005"],
          ["Able to access healthcare services (finding)", "460821000124100"],
          ["Housing security (finding)", "611211000124100"],
          ["Stably housed (finding)", "611221000124108"],
          ["Enrolled in health insurance coverage (finding)", "671271000124101"],
          ["Good attachment to primary caregiver (finding)", "713055004"],
          ["Able to manage stress (finding)", "716421004"],
          ["Able to think creatively (finding)", "716454002"],
          ["Psychological resilience (finding)", "733903006"],
          ["Increased motivation (finding)", "86808004"],
          ["Encounter for counseling for socioeconomic factors", "Z71.88"],
      ],
    }
  end

  def fetch_health_concerns
    client = get_client
    search_params = {
      parameters: {
        # category: "health-concern",
        subject: patient_id,
        _sort: "-_lastUpdated"
      }
    }

    begin
      response = client.search(FHIR::Condition, search: search_params)
      if response.response[:code] == 200
        entries = response.resource.entry
        conditions = entries.map do |entry|
          Condition.new(entry.resource, fhir_client: client)
        end

        # Grouping by category(health concerns vs problems) then by clinical status (active, inactive, resolved)
        grp =
          conditions
            .group_by(&:type)
            .transform_values { |values| values.group_by(&:clinical_status) }

        save_conditions(grp["problem-list-item"]&.dig("active"))
        [true, grp]
      else
        Rails.logger.error("Failed to fetch patient's health concerns. Status: #{response.response[:code]} - #{response.response[:body]}")

        [false, "Failed to fetch patient's health concerns. Status: #{response.response[:code]} - #{response.response[:body]}"]
      end
    rescue Errno::ECONNREFUSED => e
      Rails.logger.error(e.full_message)

      [false, "Connection refused. Please check FHIR server's URL #{get_server_base_url} is up and try again. #{e.message}"]
    rescue StandardError => e
      Rails.logger.error(e.full_message)

      [false, "Something went wrong. #{e.message}"]
    end
  end
end
